vim.keymap.set("n", "<leader>Ls", ":LivePreview start<CR>", { silent = true, desc = "[L]ive Preview [S]tart" })
vim.keymap.set("n", "<leader>Lc", ":LivePreview close<CR>", { silent = true, desc = "[L]ive Preview [C]lose" })
vim.keymap.set("n", "<leader>Lp", ":LivePreview pick<CR>", { silent = true, desc = "[L]ive Preview [P]ick file" })
vim.keymap.set("n", "<leader>Lh", ":help LivePreview<CR>", { silent = true, desc = "[L]ive Preview [H]elp" })
vim.keymap.set("n", "<leader>Lp", ":LivePreview pick<CR>", { silent = true, desc = "[L]ive Preview [P]ick" })
